catalog:
  nuxt: ^4.4.4
  typescript: ^6.0.3
  vitest: ^4.1.6
  vue: latest
  vue-tsc: ^3.2.8

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  simple-git-hooks: true
  unrs-resolver: true
  vue-demi: true